-- 1

SELECT O.ORDNO, O.ORDDATE, O.CUSTNO, C.CUSTFIRSTNAME, C.CUSTLASTNAME, O.EMPNO, E.EMPFIRSTNAME, E.EMPLASTNAME
FROM ORDERTBL AS O, EMPLOYEE AS E, CUSTOMER AS C
WHERE CUSTSTATE = 'CO' AND ORDDATE BETWEEN '2013-01-01' AND '2013-01-31';

-- 2
SELECT C.CUSTNO, C.CUSTFIRSTNAME, C.CUSTLASTNAME, O.ORDNO, ORD.ORDDATE, E.EMPNO, E.EMPFIRSTNAME, EMPLASTNAME, P.PRODNO, P.PRODNAME, (O.QTY * P.PRODPRICE)AS 'ORDER COST'
FROM CUSTOMER AS C, PRODUCT AS P, EMPLOYEE AS E, ORDLINE AS O, ORDERTBL AS ORD
WHERE ORDDATE = '2013-01-23' AND (O.QTY * P.PRODPRICE) > 150;

-- 3
SELECT OT.ORDNO, SUM(O.QTY * P.PRODPRICE) AS 'TOTAL AMOUNT'
FROM ORDLINE AS O, PRODUCT AS P, ORDERTBL AS OT
WHERE ORDDATE = '2013-01-23'
GROUP BY ORDNO;

-- 4
SELECT O.ORDNO, OT.ORDDATE, C.CUSTFIRSTNAME, C.CUSTLASTNAME, SUM(O.QTY * P.PRODPRICE) AS 'TOTAL AMOUNT'
FROM ORDLINE AS O, ORDERTBL AS OT, PRODUCT AS P, CUSTOMER AS C
WHERE ORDDATE = '2013-01-23'
GROUP BY ORDNO, ORDDATE, CUSTFIRSTNAME, CUSTLASTNAME;

-- 5
INSERT INTO CUSTOMER
(CUSTNO, CUSTFIRSTNAME, CUSTLASTNAME, CUSTSTREET, CUSTCITY, CUSTSTATE, CUSTZIP, CUSTBAL)
VALUES('C254367', 'ALEX', 'MALAN', 'DACIA', 'ORADEA', 'BH', '410339', 400);

-- 6
INSERT INTO EMPLOYEE
(EMPNO, EMPFIRSTNAME, EMPLASTNAME, EMPPHONE, EMPEMAIL, SUPEMPNO, EMPCOMMRATE)
VALUES('E2343664', 'SERGIU', 'BULZAN', 2342342, 'SERGIU@GMAIL.COM', 'EM33223', 0.0022);

-- 7
UPDATE PRODUCT
SET PRODPRICE = PRODPRICE * 1.10
WHERE PRODNAME = '%Ink Jet%';

-- 8
DELETE FROM EMPLOYEE
WHERE EMPNO = 'E2343664';