-- 1
SELECT CUSTNO, CUSTFIRSTNAME, CUSTLASTNAME, CUSTBAL
FROM CUSTOMER;

-- 2
SELECT CustNo, CustLastName, CustFirstName, CustBal
FROM Customer
WHERE CustState = 'CO';

-- 3 
SELECT *
FROM Product
WHERE ProdPrice > 50
ORDER BY ProdMfg;

-- 4
SELECT CUSTNO, CUSTFIRSTNAME, CUSTLASTNAME, CUSTCITY, CUSTBAL 
FROM CUSTOMER
WHERE (CUSTCITY='Denver' AND CUSTBAL > 150) OR (CUSTCITY='Seattle' AND CUSTBAL > 300);

-- 5
SELECT O.ORDNO, O.ORDDATE, C.CUSTNO, C.CUSTFIRSTNAME, C.CUSTLASTNAME
FROM OrderTbl AS O, Customer AS C
WHERE OrdState='CO' AND OrdDate BETWEEN '2017-01-01' AND '2017-01-31';

-- 6
SELECT CUSTCITY, AVG(CUSTBAL)
FROM CUSTOMER
WHERE CUSTSTATE='WA'
GROUP BY CUSTCITY;

-- 7
SELECT CUSTCITY, AVG(CUSTBAL), COUNT(CUSTNO)
FROM CUSTOMER
WHERE CUSTSTATE='WA'
GROUP BY CUSTCITY
HAVING COUNT(*) > 1;





