-- 1
SELECT E.EVENTNO, E.DATEHELD, E.CUSTNO, E.FACNO, F.FACNAME
FROM EVENTREQUEST AS E, FACILITY AS F, CUSTOMER
WHERE DATEHELD LIKE '2018-%' AND CITY = 'Boulder';

-- 2
SELECT C.CUSTNO, C.CUSTNAME, E.EVENTNO, (E.ESTCOST/E.ESTAUDIENCE) AS 'EST'
FROM EVENTREQUEST AS E, CUSTOMER AS C
WHERE DATEHELD LIKE '2018-%' AND 'EST' < 0.2; 

-- 3
SELECT C.CUSTNO, C.CUSTNAME, SUM(E.ESTCOST) AS 'SUM'
FROM CUSTOMER AS C, EVENTREQUEST AS E
WHERE STATUS = 'Approved'
GROUP BY CUSTNO, CUSTNAME;

-- 4
INSERT INTO CUSTOMER
(CUSTNO, CUSTNAME, ADDRESS, INTERNAL, CONTACT, PHONE, CITY, STATE, ZIP)
VALUES('C106', 'Alex Malan', 'icarus road', 'Y', '4563453', '3264575', 'Washington', 'WA', '44432');

-- 5
UPDATE RESOURCETBL
SET RATE = RATE + (100+10)/100
WHERE RESNAME = 'nurse';

-- 6
DELETE FROM CUSTOMER
WHERE CUSTNAME = 'Alex Malan';