-- 1 
SELECT CUSTNO, CUSTNAME, PHONE, CITY
FROM CUSTOMER;

-- 2
SELECT CUSTNO, CUSTNAME, PHONE, CITY
FROM CUSTOMER
WHERE STATE = "CO";

-- 3
SELECT *
FROM EVENTREQUEST
WHERE ESTCOST > 4000
ORDER BY DATEHELD;

-- 4 
SELECT EVENTNO, DATEHELD, ESTAUDIENCE
FROM EVENTREQUEST
WHERE (STATUS = 'Approved' AND ESTAUDIENCE > 9000) OR (STATUS = 'Pending' AND ESTAUDIENCE > 4000);

-- 5
SELECT E.EVENTNO, E.DATEHELD, C.CUSTNO, C.CUSTNAME
FROM EVENTREQUEST AS E
INNER JOIN CUSTOMER AS C
WHERE DATEHELD BETWEEN '2018-01-01' AND '2018-01-31' AND CITY = 'BOULDER';

-- 6
SELECT AVG(NUMBERFLD)
FROM EVENTPLANLINE
WHERE LOCNO = 'L100';

-- 7
SELECT AVG(NUMBERFLD) 
FROM EVENTPLANLINE
WHERE LOCNO = 'L100';
